export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  category: 'Physical Therapy' | 'Occupational Therapy' | 'Speech Therapy' | 'Family & Caregivers' | 'Wellness at Home';
  readTime: string;
  date: string;
  author: string;
  image: string;
  imageAlt: string;
  body: string[];
  takeaways: string[];
}

// Unsplash imagery — free to use under the Unsplash License.
// Chosen for calm, warm, editorial tone: nature, home interiors, hands, textures.
export const POSTS: BlogPost[] = [
  {
    slug: 'starting-in-home-physical-therapy',
    title: 'What to expect when you start in-home physical therapy',
    excerpt: 'A gentle walkthrough of the first visit — the questions we ask, the room we set up, and the small goals that come first.',
    category: 'Physical Therapy',
    readTime: '6 min read',
    date: 'August 4, 2025',
    author: 'The Care and Protect Team',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1600&q=80',
    imageAlt: 'Soft morning light through sheer curtains onto a wooden floor',
    body: [
      'The first visit is quieter than most people expect. There is no waiting room, no clipboard on the wall, no fluorescent hum. We sit at your kitchen table or in the room where daily life happens, and we talk for a while before anyone lifts a leg or squeezes a hand.',
      'That conversation is the treatment plan in disguise. We ask about the stairs you use, the chair you rise from, the moments in the day when your body feels most reluctant. Every home has its own choreography — the shower step, the second-floor hallway, the doorway where the rug lifts a little. Our work maps to that terrain.',
      'When we begin the physical assessment, we go slowly. Range of motion, balance, endurance, and pain are measured against comfort — not clinical targets. Nothing is rushed. If something is too much, we stop and rebuild the plan around what you can do today, not what you did last year.',
      'By the end of the first visit, we usually leave you with two or three small movements to practice. Not a program. Not homework. Small, deliberate things you can fit into an existing routine — a heel raise while the kettle boils, a hip hinge before sitting on the couch.',
    ],
    takeaways: [
      'The first session is largely conversation and observation, not exertion.',
      'Care is designed around your home, not a clinic room.',
      'Progress starts with 2–3 small, repeatable movements.',
    ],
  },
  {
    slug: 'occupational-therapy-daily-living',
    title: 'Occupational therapy: the quiet work of daily living',
    excerpt: 'Buttons, mugs, showers, shoelaces. The details of an ordinary day are where independence lives — and where OT begins.',
    category: 'Occupational Therapy',
    readTime: '5 min read',
    date: 'July 22, 2025',
    author: 'The Care and Protect Team',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1600&q=80',
    imageAlt: 'A warm ceramic mug held in two hands beside a book',
    body: [
      'Occupational therapy is often misunderstood as being about occupations — jobs, careers, work. In fact, the word refers to the things that occupy your day. Getting dressed. Making breakfast. Reaching for a glass. Writing a note by the phone.',
      'When one of those small tasks becomes hard, the whole rhythm of a day changes. A person who cannot easily button a shirt begins to avoid buttoned shirts. Someone who struggles with a heavy pan stops cooking the meals they love. The world quietly narrows.',
      'An occupational therapist widens it again. We look at the task, the body, and the environment as a single system — and we adjust the piece that gives most easily. Sometimes that is a technique. Sometimes it is a tool. Sometimes it is a change to the room. Almost always, it is the smallest change that works.',
      'By the time we leave, the shirt has buttons again. The pan is back on the stove. The note gets written.',
    ],
    takeaways: [
      'OT centers on the everyday tasks that make up a life.',
      'Small tools and technique changes often outperform effort.',
      'Independence is often about restoring one specific step in a chain.',
    ],
  },
  {
    slug: 'speech-therapy-adults-swallowing',
    title: 'Speech therapy for adults — beyond speaking',
    excerpt: 'Swallowing, memory, voice, comprehension. Adult speech therapy is a broad field, and much of it happens quietly at home.',
    category: 'Speech Therapy',
    readTime: '7 min read',
    date: 'July 10, 2025',
    author: 'The Care and Protect Team',
    image: 'https://images.unsplash.com/photo-1544027993-37dbfe43562a?auto=format&fit=crop&w=1600&q=80',
    imageAlt: 'A bowl of warm broth on a linen tablecloth',
    body: [
      'When people think of speech therapy, they often picture a child working on the letter R. But for adults — particularly after a stroke, a diagnosis of dementia, or a long illness — speech therapy can be about much more than pronunciation.',
      'Swallowing is one of the most common reasons an adult sees a speech-language pathologist. A safe swallow is a coordinated act involving muscles, timing, and attention. When any of those slip, mealtimes become effortful and, in some cases, unsafe. We work with foods and liquids as they actually appear at your table — not in a clinic.',
      'Voice and word-finding are the other quiet frontier. A voice that has grown thin, or a mind that reaches for the right noun and comes back empty-handed, can be gently retrained. The exercises are small: a few minutes a day, folded into conversations you were already going to have.',
      'The goal is never to sound like someone you were twenty years ago. It is to be heard, understood, and nourished today.',
    ],
    takeaways: [
      'Speech therapy for adults covers swallowing, voice, memory, and comprehension.',
      'Home-based sessions use your real meals and real conversations.',
      'Short, regular practice beats long, exhausting sessions.',
    ],
  },
  {
    slug: 'preventing-falls-at-home',
    title: 'Preventing falls at home: a room-by-room walkthrough',
    excerpt: 'The rug at the bathroom door. The step to the porch. The lamp cord across the hallway. Where falls actually happen — and how to head them off.',
    category: 'Wellness at Home',
    readTime: '8 min read',
    date: 'June 28, 2025',
    author: 'The Care and Protect Team',
    image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1600&q=80',
    imageAlt: 'A sunlit hallway with wood floors and a small side table',
    body: [
      'Most falls at home are not dramatic. They happen in a familiar hallway, on a step someone has climbed for thirty years, on a rug that was fine yesterday. The hazard is rarely a single object — it is the interaction between the person, the surface, the light, and the moment.',
      'The bathroom is where we usually start. Wet tile, low light, small floor area. A grab bar near the toilet and one inside the shower is often enough to change the risk profile of the whole room. Non-slip mats matter — but only if they actually grip.',
      'Bedrooms hide risks in the transitions: getting up in the night, reaching for a light switch, stepping over a chargingg cable. A soft nightlight and a clear path to the bathroom eliminate more falls than any single piece of equipment we can install.',
      'Living rooms and stairs are about edges — the corner of a coffee table, the top step of a stair, the lip of a threshold between two rooms. Contrasting tape on stair edges is unglamorous and completely effective.',
    ],
    takeaways: [
      'Falls almost always happen in familiar rooms during routine moments.',
      'Bathrooms and stairs are the two highest-risk zones.',
      'Lighting and contrast prevent more falls than most equipment.',
    ],
  },
  {
    slug: 'stroke-recovery-first-90-days',
    title: 'Stroke recovery at home: the first ninety days',
    excerpt: 'The window of fastest change — and the window that matters most for family, therapists, and the person recovering.',
    category: 'Physical Therapy',
    readTime: '9 min read',
    date: 'June 12, 2025',
    author: 'The Care and Protect Team',
    image: 'https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=1600&q=80',
    imageAlt: 'A quiet forest path with soft morning mist',
    body: [
      'The first three months after a stroke are unlike any other period in a person\'s life. The brain is more plastic than it will be again. Small, consistent inputs — a movement repeated, a word practiced, a step taken with support — can rewire capacities that seemed lost the day of discharge.',
      'That is why we start early. Not aggressively — the body has been through something profound — but early. The first week home is about safety, sleep, and a very short list of daily movements. The second week we add one thing. Then another.',
      'Family members are part of the plan from the beginning. Not as unpaid caregivers, but as coaches — the people who see the progress that a weekly visit misses. We teach the cues, the safe grip, the moment to encourage and the moment to step back.',
      'Ninety days is not an endpoint. It is a window. What happens inside it shapes what is possible for the next several years — and that is worth building around.',
    ],
    takeaways: [
      'Neuroplasticity is highest in the first 90 days after a stroke.',
      'Small, daily, consistent practice outperforms occasional intensity.',
      'Family coaching is a critical part of the therapy plan.',
    ],
  },
  {
    slug: 'chronic-pain-gentle-movement',
    title: 'Chronic pain: why gentle movement is often the answer',
    excerpt: 'The instinct to protect a painful body is right. The habit of not moving it is not. A careful middle path.',
    category: 'Physical Therapy',
    readTime: '6 min read',
    date: 'May 30, 2025',
    author: 'The Care and Protect Team',
    image: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=1600&q=80',
    imageAlt: 'A woman stretching gently on a mat in warm morning light',
    body: [
      'Chronic pain teaches the body to guard. Muscles brace, joints stiffen, and a person begins — often without noticing — to avoid the movements that once felt easy. It is a rational response to a signal that never quite turns off, and over time it becomes its own problem.',
      'The evidence has been steady for years: gentle, sustained, well-dosed movement is one of the most effective long-term treatments for chronic pain. Not aggressive exercise. Not pushing through. Careful movement, done consistently, tuned to how the body feels today.',
      'What that looks like in practice is small. A short walk on a good day. A few minutes of mobility work in the morning. A stretch during a commercial break. The dose matters less than the fact that it happens.',
      'Our job is to find the dose that a body will actually accept, and to help it grow — a little wider, a little more confident — week by week.',
    ],
    takeaways: [
      'Guarding is a natural response that becomes counterproductive over time.',
      'Consistent, gentle movement is the best-supported long-term intervention.',
      'The goal is a dose the body will accept, not the largest possible dose.',
    ],
  },
  {
    slug: 'dementia-care-at-home',
    title: 'Dementia care at home: keeping days steady',
    excerpt: 'Rhythms, cues, and quiet environments — what makes a day easier for someone living with cognitive change.',
    category: 'Family & Caregivers',
    readTime: '7 min read',
    date: 'May 14, 2025',
    author: 'The Care and Protect Team',
    image: 'https://images.unsplash.com/photo-1512314889357-e157c22f938d?auto=format&fit=crop&w=1600&q=80',
    imageAlt: 'A pair of hands holding a warm cup of tea on a wooden table',
    body: [
      'A person with dementia does best when the day has a shape. Not a schedule pinned to the fridge, but a rhythm — a sequence of familiar cues that don\'t require memory to follow. Morning light. The same mug. A song that plays while breakfast is made.',
      'We work with families to build these rhythms in the least disruptive way possible. Big changes are hard. Small, layered changes — one this month, one the next — tend to stick.',
      'The environment matters more than most people realize. Lower background noise. Softer light in the evenings. Fewer choices where a choice is not necessary. Each of these reduces the cognitive load of the day, which is another way of saying it protects the energy the person has for the things they enjoy.',
      'The goal is not to slow the disease. It is to protect the good hours, and to make the hard ones a little less hard.',
    ],
    takeaways: [
      'Predictable rhythms outperform rigid schedules.',
      'Environmental adjustments reduce cognitive load throughout the day.',
      'Small, layered changes are more sustainable than large overhauls.',
    ],
  },
  {
    slug: 'grip-strength-why-it-matters',
    title: 'Grip strength: a small measurement with a long story',
    excerpt: 'How much you can hold in your hand turns out to say a surprising amount about how you will age.',
    category: 'Wellness at Home',
    readTime: '5 min read',
    date: 'April 29, 2025',
    author: 'The Care and Protect Team',
    image: 'https://images.unsplash.com/photo-1516382799247-87df95d790b7?auto=format&fit=crop&w=1600&q=80',
    imageAlt: 'A hand resting on a wooden railing outdoors',
    body: [
      'Grip strength has become one of the most quietly powerful markers in longevity research. It correlates with mobility, fall risk, cognitive resilience, and independence years later. It is easy to measure and, more importantly, it is trainable at almost any age.',
      'A weaker grip is not usually about the hand. It is about the whole chain — forearm, shoulder, core — and about the daily activities that used to keep those tissues loaded. When people stop carrying groceries, opening jars, and lifting laundry baskets, the grip fades. When they start again, it comes back.',
      'The exercises are unglamorous. Hanging from a bar for a few seconds. Squeezing a soft ball. Carrying two heavier bags for a longer walk. Done a few times a week, over months, they change the trajectory of what the hands can do.',
      'If your loved one has been quietly avoiding the jar lid, this is a place to start.',
    ],
    takeaways: [
      'Grip strength is a strong predictor of long-term independence.',
      'The chain from hand to shoulder to core determines grip capacity.',
      'Consistent, low-effort loading rebuilds grip at any age.',
    ],
  },
  {
    slug: 'family-caregivers-avoiding-burnout',
    title: 'Family caregivers: the quiet work of not burning out',
    excerpt: 'Caring for a parent, a partner, a sibling — the love is easy; the sustainability is harder.',
    category: 'Family & Caregivers',
    readTime: '8 min read',
    date: 'April 15, 2025',
    author: 'The Care and Protect Team',
    image: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=1600&q=80',
    imageAlt: 'A cozy reading corner with a lamp and a linen chair',
    body: [
      'Family caregivers do work that would be a full-time job even if the person receiving care were a stranger. When the person is your mother, your husband, or your brother, the work is layered with love, grief, memory, and often quiet resentment — and no one prepares you for that combination.',
      'The single most important thing we tell caregivers is that rest is not selfish. It is structural. A person who never stops caring will run out of capacity to care, and the person who depends on them will feel that shortage.',
      'Small structures help. A standing hour when someone else is in the house. A morning routine that does not begin with the person you care for. A weekly meal that is not one you cooked. These are not indulgences. They are the load-bearing parts of a caregiving life that lasts.',
      'Ask for help earlier than you think you need to. Accept help when it is offered, even in small forms. The people around you would rather hold something small this week than watch you collapse next month.',
    ],
    takeaways: [
      'Caregiver rest is structural, not indulgent.',
      'Regular, protected time off prevents collapse.',
      'Small offers of help are worth accepting.',
    ],
  },
  {
    slug: 'sleep-and-recovery',
    title: 'Sleep, and why therapy plans have to respect it',
    excerpt: 'The body does its most important repair work while you sleep. Any therapy plan that ignores that will underdeliver.',
    category: 'Wellness at Home',
    readTime: '6 min read',
    date: 'April 2, 2025',
    author: 'The Care and Protect Team',
    image: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&w=1600&q=80',
    imageAlt: 'A softly lit bedroom with linen sheets and morning light',
    body: [
      'The tissue changes that make physical therapy work — the small adaptations in muscle, tendon, and nervous system — happen mostly while you sleep. So do the memory consolidations that make speech therapy stick, and the fine-motor learning that occupational therapy depends on.',
      'A person who is not sleeping well will not progress well. It is that simple, and it is why we treat sleep as part of the plan, not as a lifestyle topic.',
      'The interventions are practical. Consistent bedtime, however unfashionable. Less light in the last hour. A cooler bedroom. A wind-down that isn\'t a screen. And, where medical conditions are getting in the way — pain, breathing, restlessness — a conversation with a physician.',
      'Sometimes the fastest way to unlock a plateau in therapy is not to add more therapy. It is to sleep an hour more, more consistently.',
    ],
    takeaways: [
      'Recovery from therapy sessions happens largely during sleep.',
      'Consistency of sleep matters more than total hours.',
      'Sleep should be treated as part of the therapy plan.',
    ],
  },
  {
    slug: 'home-safety-checklist',
    title: 'A quiet home-safety checklist for aging in place',
    excerpt: 'Not a hospital retrofit. Fifteen small changes that make a home safer without making it feel clinical.',
    category: 'Wellness at Home',
    readTime: '7 min read',
    date: 'March 20, 2025',
    author: 'The Care and Protect Team',
    image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1600&q=80',
    imageAlt: 'A warm, welcoming home entryway with soft light',
    body: [
      'Homes that have been safely retrofitted for aging do not look like hospitals. They look like homes that someone has cared for. Better lighting. Warmer floors. A grab bar that matches the towel rail. A step painted just a slightly different color at the edge.',
      'Start at the front door and walk through the house the way a visitor would, once at eye level and once from a seated position. Ask two questions of every space: is the path clear, and is the surface predictable?',
      'The bathroom is the highest priority — grab bars, a non-slip mat, a shower seat if standing has become effortful, brighter lighting for the mirror. The kitchen is second — sharp knife storage, lever handles on cabinets, a stool for the reachable shelf.',
      'None of this should feel like a takeover of the house. Every change should read as care, not surveillance.',
    ],
    takeaways: [
      'Aging-in-place changes should look and feel like design, not medical equipment.',
      'Bathroom and kitchen are the highest-priority rooms.',
      'The goal is safety without loss of dignity or aesthetics.',
    ],
  },
  {
    slug: 'parkinsons-daily-movement',
    title: 'Parkinson\'s and the case for daily movement',
    excerpt: 'Big, deliberate, expressive movement — done every day — remains one of the most powerful tools we have.',
    category: 'Physical Therapy',
    readTime: '7 min read',
    date: 'March 6, 2025',
    author: 'The Care and Protect Team',
    image: 'https://images.unsplash.com/photo-1552196563-55cd4e45efb3?auto=format&fit=crop&w=1600&q=80',
    imageAlt: 'A person walking through a golden field at sunset',
    body: [
      'Parkinson\'s disease teaches the body to make itself smaller. Steps shorten. Voices soften. Handwriting shrinks. Left alone, the loop tightens on itself.',
      'A large body of evidence supports a different kind of practice: exaggerated, deliberate, whole-body movement, done daily. Big steps. Loud voice. Wide arm swings. When those become part of a routine, the disease\'s natural pull toward smallness is answered every day by a pull in the other direction.',
      'What this looks like at home is not dramatic. A ten-minute morning walk with deliberate long strides. Reading a short passage aloud, projecting to the far wall. Reaching, stretching, doing one thing bigger than it needs to be.',
      'The disease does what it does. But the response, done consistently, changes what daily life looks like — and that is the fight worth having.',
    ],
    takeaways: [
      'Parkinson\'s tends to reduce movement amplitude — a trend worth resisting.',
      'Deliberately large, daily movement is well supported by research.',
      'Consistency matters more than the length of any single session.',
    ],
  },
  {
    slug: 'child-speech-development-home',
    title: 'Encouraging a child\'s speech development at home',
    excerpt: 'The quiet, ordinary moments — bath time, meals, walks — are where language grows fastest.',
    category: 'Speech Therapy',
    readTime: '5 min read',
    date: 'February 20, 2025',
    author: 'The Care and Protect Team',
    image: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&w=1600&q=80',
    imageAlt: 'A collection of picture books and a small wooden toy',
    body: [
      'Children build language not in flashcard drills but in the middle of ordinary life — narrated, sung, repeated, and gently expanded. The most powerful thing a parent can do is talk about what the child is already paying attention to.',
      'If a child points to a dog, we say "dog" — and then, a second later, "big brown dog." That small expansion is a whole language lesson wrapped inside a shared moment. Done a hundred times a day, it does more than any curriculum.',
      'Reading matters — but so does noticing. Naming the ingredients as you cook, describing the weather on the walk to the mailbox, singing the same three songs in the car. Repetition is the engine of language acquisition, not a sign of a stalled process.',
      'If something feels off — a milestone missed, a sound consistently produced differently — we\'d rather see you early than late. The tools we have work best when there is time.',
    ],
    takeaways: [
      'Language grows fastest inside ordinary, shared moments.',
      'Repetition and gentle expansion are the two most powerful techniques.',
      'Early evaluation is preferable to a "wait and see" approach.',
    ],
  },
  {
    slug: 'adaptive-tools-independence',
    title: 'The quiet power of adaptive tools',
    excerpt: 'A jar opener. A long-handled shoehorn. A weighted spoon. Small pieces of design that give a day back.',
    category: 'Occupational Therapy',
    readTime: '5 min read',
    date: 'February 5, 2025',
    author: 'The Care and Protect Team',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=1600&q=80',
    imageAlt: 'A calm, well-organized kitchen counter with simple utensils',
    body: [
      'Adaptive tools have a public relations problem. In pictures, they look institutional. In use, they look like design. A weighted spoon in a warm walnut handle. A jar opener that lives in a drawer next to the corkscrew. A shoehorn long enough that no one has to bend.',
      'What each of these tools does is remove one small barrier — a barrier that had, quietly, been shaping a day. When a barrier is removed, the activity comes back. Meals become meals again. Shoes go on without a fifteen-minute production.',
      'We spend time in occupational therapy matching the right tool to the right person. There are surprisingly bad options on the market. There are also excellent ones, and we know where they are.',
      'The best adaptive tools are the ones a person forgets are adaptive at all.',
    ],
    takeaways: [
      'Good adaptive tools remove a single specific barrier.',
      'Design and materials matter — well-chosen tools blend into the home.',
      'The right tool restores an activity, not just a capability.',
    ],
  },
  {
    slug: 'nutrition-and-therapy-outcomes',
    title: 'Nutrition, quietly, is part of every therapy plan',
    excerpt: 'The best exercise plan in the world will underdeliver without the fuel to support it.',
    category: 'Wellness at Home',
    readTime: '6 min read',
    date: 'January 22, 2025',
    author: 'The Care and Protect Team',
    image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=1600&q=80',
    imageAlt: 'A wooden board with fresh vegetables, herbs, and olive oil',
    body: [
      'The tissues that therapy asks a body to rebuild — muscle, tendon, brain — are made out of what a person eats. Protein especially. Older adults, in particular, tend to under-eat protein without realizing it, and the effect on therapy outcomes is real.',
      'We don\'t hand out meal plans. We\'re not dietitians. But we do ask about meals, because the answer is often the missing variable in a plateau. A person who is trying to rebuild strength on toast and tea will make less progress than a person eating simple, protein-rich meals three times a day.',
      'The changes we recommend are small. A boiled egg with breakfast. A palm-sized portion of protein at lunch. Yogurt or nuts in the afternoon. Water — deliberate, glass-by-glass — through the day.',
      'When nutrition is quietly right, everything else in the plan works better.',
    ],
    takeaways: [
      'Under-eating protein is a common invisible ceiling on therapy progress.',
      'Small, consistent additions outperform major dietary overhauls.',
      'Hydration is part of the plan, not a separate topic.',
    ],
  },
  {
    slug: 'returning-to-driving-after-illness',
    title: 'Returning to driving after illness or injury',
    excerpt: 'For many people, the car is not transport — it is independence. Coming back to it deserves a careful path.',
    category: 'Occupational Therapy',
    readTime: '6 min read',
    date: 'January 8, 2025',
    author: 'The Care and Protect Team',
    image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1600&q=80',
    imageAlt: 'A quiet country road at golden hour',
    body: [
      'Very few things return as much life as being able to drive again. Groceries. Grandchildren. Coffee with a friend. The freedom to leave the house on your own terms. For many of our clients, that is what recovery is actually for.',
      'Returning to driving is not a single question. It is several — vision, reaction time, cognition, physical range of motion, and, quietly, confidence. Each can be assessed. Each can, in most cases, be improved.',
      'We do not clear people to drive. That decision belongs to physicians and, in some cases, to state licensing bodies. What we do is help a person prepare — build the physical capacity, practice the cognitive tasks, and know honestly where they stand.',
      'Sometimes the answer is "not yet." Sometimes it is "yes, in three months, if we do this work." Almost never is it "never." And the path back is usually shorter than people fear.',
    ],
    takeaways: [
      'Driving is often the most life-changing capability to recover.',
      'Multiple systems — physical, cognitive, visual — need to be assessed.',
      'The path back is real, and usually shorter than clients expect.',
    ],
  },
];
